#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_SQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Nhom_Solo")]
	public partial class KhachHangClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietDonHang(ChiTietDonHang instance);
    partial void UpdateChiTietDonHang(ChiTietDonHang instance);
    partial void DeleteChiTietDonHang(ChiTietDonHang instance);
    partial void InsertDonHang(DonHang instance);
    partial void UpdateDonHang(DonHang instance);
    partial void DeleteDonHang(DonHang instance);
    partial void InsertQuanLy(QuanLy instance);
    partial void UpdateQuanLy(QuanLy instance);
    partial void DeleteQuanLy(QuanLy instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertDanhGiaSach(DanhGiaSach instance);
    partial void UpdateDanhGiaSach(DanhGiaSach instance);
    partial void DeleteDanhGiaSach(DanhGiaSach instance);
    partial void InsertGioHang(GioHang instance);
    partial void UpdateGioHang(GioHang instance);
    partial void DeleteGioHang(GioHang instance);
    partial void InsertPhieuXuat(PhieuXuat instance);
    partial void UpdatePhieuXuat(PhieuXuat instance);
    partial void DeletePhieuXuat(PhieuXuat instance);
    partial void InsertChiTietPhieuXuat(ChiTietPhieuXuat instance);
    partial void UpdateChiTietPhieuXuat(ChiTietPhieuXuat instance);
    partial void DeleteChiTietPhieuXuat(ChiTietPhieuXuat instance);
    #endregion
		
		public KhachHangClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KhachHangClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KhachHangClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KhachHangClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietDonHang> ChiTietDonHangs
		{
			get
			{
				return this.GetTable<ChiTietDonHang>();
			}
		}
		
		public System.Data.Linq.Table<DonHang> DonHangs
		{
			get
			{
				return this.GetTable<DonHang>();
			}
		}
		
		public System.Data.Linq.Table<QuanLy> QuanLies
		{
			get
			{
				return this.GetTable<QuanLy>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<DanhGiaSach> DanhGiaSaches
		{
			get
			{
				return this.GetTable<DanhGiaSach>();
			}
		}
		
		public System.Data.Linq.Table<GioHang> GioHangs
		{
			get
			{
				return this.GetTable<GioHang>();
			}
		}
		
		public System.Data.Linq.Table<PhieuXuat> PhieuXuats
		{
			get
			{
				return this.GetTable<PhieuXuat>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietPhieuXuat> ChiTietPhieuXuats
		{
			get
			{
				return this.GetTable<ChiTietPhieuXuat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Orders.ChiTietDonHang")]
	public partial class ChiTietDonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CTDH_ID;
		
		private int _CTDH_SachID;
		
		private System.Nullable<int> _CTDH_SoLuong;
		
		private System.Nullable<decimal> _CTDH_ThanhTien;
		
		private int _CTDH_DonHangID;
		
		private System.Guid _rowguid;
		
		private EntityRef<DonHang> _DonHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCTDH_IDChanging(int value);
    partial void OnCTDH_IDChanged();
    partial void OnCTDH_SachIDChanging(int value);
    partial void OnCTDH_SachIDChanged();
    partial void OnCTDH_SoLuongChanging(System.Nullable<int> value);
    partial void OnCTDH_SoLuongChanged();
    partial void OnCTDH_ThanhTienChanging(System.Nullable<decimal> value);
    partial void OnCTDH_ThanhTienChanged();
    partial void OnCTDH_DonHangIDChanging(int value);
    partial void OnCTDH_DonHangIDChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public ChiTietDonHang()
		{
			this._DonHang = default(EntityRef<DonHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTDH_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CTDH_ID
		{
			get
			{
				return this._CTDH_ID;
			}
			set
			{
				if ((this._CTDH_ID != value))
				{
					this.OnCTDH_IDChanging(value);
					this.SendPropertyChanging();
					this._CTDH_ID = value;
					this.SendPropertyChanged("CTDH_ID");
					this.OnCTDH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTDH_SachID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CTDH_SachID
		{
			get
			{
				return this._CTDH_SachID;
			}
			set
			{
				if ((this._CTDH_SachID != value))
				{
					this.OnCTDH_SachIDChanging(value);
					this.SendPropertyChanging();
					this._CTDH_SachID = value;
					this.SendPropertyChanged("CTDH_SachID");
					this.OnCTDH_SachIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTDH_SoLuong", DbType="Int")]
		public System.Nullable<int> CTDH_SoLuong
		{
			get
			{
				return this._CTDH_SoLuong;
			}
			set
			{
				if ((this._CTDH_SoLuong != value))
				{
					this.OnCTDH_SoLuongChanging(value);
					this.SendPropertyChanging();
					this._CTDH_SoLuong = value;
					this.SendPropertyChanged("CTDH_SoLuong");
					this.OnCTDH_SoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTDH_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> CTDH_ThanhTien
		{
			get
			{
				return this._CTDH_ThanhTien;
			}
			set
			{
				if ((this._CTDH_ThanhTien != value))
				{
					this.OnCTDH_ThanhTienChanging(value);
					this.SendPropertyChanging();
					this._CTDH_ThanhTien = value;
					this.SendPropertyChanged("CTDH_ThanhTien");
					this.OnCTDH_ThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTDH_DonHangID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CTDH_DonHangID
		{
			get
			{
				return this._CTDH_DonHangID;
			}
			set
			{
				if ((this._CTDH_DonHangID != value))
				{
					if (this._DonHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCTDH_DonHangIDChanging(value);
					this.SendPropertyChanging();
					this._CTDH_DonHangID = value;
					this.SendPropertyChanged("CTDH_DonHangID");
					this.OnCTDH_DonHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonHang_ChiTietDonHang", Storage="_DonHang", ThisKey="CTDH_DonHangID", OtherKey="DH_ID", IsForeignKey=true)]
		public DonHang DonHang
		{
			get
			{
				return this._DonHang.Entity;
			}
			set
			{
				DonHang previousValue = this._DonHang.Entity;
				if (((previousValue != value) 
							|| (this._DonHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonHang.Entity = null;
						previousValue.ChiTietDonHangs.Remove(this);
					}
					this._DonHang.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonHangs.Add(this);
						this._CTDH_DonHangID = value.DH_ID;
					}
					else
					{
						this._CTDH_DonHangID = default(int);
					}
					this.SendPropertyChanged("DonHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Orders.DonHang")]
	public partial class DonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DH_ID;
		
		private System.Nullable<int> _DH_KhachHangId;
		
		private System.Nullable<System.DateTime> _DH_Ngay;
		
		private System.Nullable<decimal> _DH_ThanhTien;
		
		private System.Nullable<bool> _DH_TrangThai;
		
		private System.Guid _rowguid;
		
		private EntitySet<ChiTietDonHang> _ChiTietDonHangs;
		
		private EntityRef<PhieuXuat> _PhieuXuat;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDH_IDChanging(int value);
    partial void OnDH_IDChanged();
    partial void OnDH_KhachHangIdChanging(System.Nullable<int> value);
    partial void OnDH_KhachHangIdChanged();
    partial void OnDH_NgayChanging(System.Nullable<System.DateTime> value);
    partial void OnDH_NgayChanged();
    partial void OnDH_ThanhTienChanging(System.Nullable<decimal> value);
    partial void OnDH_ThanhTienChanged();
    partial void OnDH_TrangThaiChanging(System.Nullable<bool> value);
    partial void OnDH_TrangThaiChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public DonHang()
		{
			this._ChiTietDonHangs = new EntitySet<ChiTietDonHang>(new Action<ChiTietDonHang>(this.attach_ChiTietDonHangs), new Action<ChiTietDonHang>(this.detach_ChiTietDonHangs));
			this._PhieuXuat = default(EntityRef<PhieuXuat>);
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DH_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DH_ID
		{
			get
			{
				return this._DH_ID;
			}
			set
			{
				if ((this._DH_ID != value))
				{
					this.OnDH_IDChanging(value);
					this.SendPropertyChanging();
					this._DH_ID = value;
					this.SendPropertyChanged("DH_ID");
					this.OnDH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DH_KhachHangId", DbType="Int")]
		public System.Nullable<int> DH_KhachHangId
		{
			get
			{
				return this._DH_KhachHangId;
			}
			set
			{
				if ((this._DH_KhachHangId != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDH_KhachHangIdChanging(value);
					this.SendPropertyChanging();
					this._DH_KhachHangId = value;
					this.SendPropertyChanged("DH_KhachHangId");
					this.OnDH_KhachHangIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DH_Ngay", DbType="DateTime")]
		public System.Nullable<System.DateTime> DH_Ngay
		{
			get
			{
				return this._DH_Ngay;
			}
			set
			{
				if ((this._DH_Ngay != value))
				{
					this.OnDH_NgayChanging(value);
					this.SendPropertyChanging();
					this._DH_Ngay = value;
					this.SendPropertyChanged("DH_Ngay");
					this.OnDH_NgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DH_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> DH_ThanhTien
		{
			get
			{
				return this._DH_ThanhTien;
			}
			set
			{
				if ((this._DH_ThanhTien != value))
				{
					this.OnDH_ThanhTienChanging(value);
					this.SendPropertyChanging();
					this._DH_ThanhTien = value;
					this.SendPropertyChanged("DH_ThanhTien");
					this.OnDH_ThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DH_TrangThai", DbType="Bit")]
		public System.Nullable<bool> DH_TrangThai
		{
			get
			{
				return this._DH_TrangThai;
			}
			set
			{
				if ((this._DH_TrangThai != value))
				{
					this.OnDH_TrangThaiChanging(value);
					this.SendPropertyChanging();
					this._DH_TrangThai = value;
					this.SendPropertyChanged("DH_TrangThai");
					this.OnDH_TrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonHang_ChiTietDonHang", Storage="_ChiTietDonHangs", ThisKey="DH_ID", OtherKey="CTDH_DonHangID")]
		public EntitySet<ChiTietDonHang> ChiTietDonHangs
		{
			get
			{
				return this._ChiTietDonHangs;
			}
			set
			{
				this._ChiTietDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonHang_PhieuXuat", Storage="_PhieuXuat", ThisKey="DH_ID", OtherKey="PX_ID", IsUnique=true, IsForeignKey=false)]
		public PhieuXuat PhieuXuat
		{
			get
			{
				return this._PhieuXuat.Entity;
			}
			set
			{
				PhieuXuat previousValue = this._PhieuXuat.Entity;
				if (((previousValue != value) 
							|| (this._PhieuXuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuXuat.Entity = null;
						previousValue.DonHang = null;
					}
					this._PhieuXuat.Entity = value;
					if ((value != null))
					{
						value.DonHang = this;
					}
					this.SendPropertyChanged("PhieuXuat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonHang", Storage="_KhachHang", ThisKey="DH_KhachHangId", OtherKey="KH_ID", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DonHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DonHangs.Add(this);
						this._DH_KhachHangId = value.KH_ID;
					}
					else
					{
						this._DH_KhachHangId = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDonHangs(ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.DonHang = this;
		}
		
		private void detach_ChiTietDonHangs(ChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.DonHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Users.QuanLy")]
	public partial class QuanLy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QL_ID;
		
		private string _QL_TenTruyCap;
		
		private string _QL_Email;
		
		private string _QL_MatKhau;
		
		private System.Nullable<System.DateTime> _QL_NgayBatDau;
		
		private string _QL_Hoten;
		
		private string _QL_CCCD;
		
		private System.Nullable<System.DateTime> _QL_NgaySinh;
		
		private System.Nullable<int> _QL_GioiTinh;
		
		private string _QL_DiaChi;
		
		private string _QL_DienThoai;
		
		private System.Nullable<byte> _QL_Quyen;
		
		private System.Nullable<bool> _QL_TrangThai;
		
		private string _QL_KhuVuc;
		
		private System.Guid _rowguid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQL_IDChanging(int value);
    partial void OnQL_IDChanged();
    partial void OnQL_TenTruyCapChanging(string value);
    partial void OnQL_TenTruyCapChanged();
    partial void OnQL_EmailChanging(string value);
    partial void OnQL_EmailChanged();
    partial void OnQL_MatKhauChanging(string value);
    partial void OnQL_MatKhauChanged();
    partial void OnQL_NgayBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnQL_NgayBatDauChanged();
    partial void OnQL_HotenChanging(string value);
    partial void OnQL_HotenChanged();
    partial void OnQL_CCCDChanging(string value);
    partial void OnQL_CCCDChanged();
    partial void OnQL_NgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnQL_NgaySinhChanged();
    partial void OnQL_GioiTinhChanging(System.Nullable<int> value);
    partial void OnQL_GioiTinhChanged();
    partial void OnQL_DiaChiChanging(string value);
    partial void OnQL_DiaChiChanged();
    partial void OnQL_DienThoaiChanging(string value);
    partial void OnQL_DienThoaiChanged();
    partial void OnQL_QuyenChanging(System.Nullable<byte> value);
    partial void OnQL_QuyenChanged();
    partial void OnQL_TrangThaiChanging(System.Nullable<bool> value);
    partial void OnQL_TrangThaiChanged();
    partial void OnQL_KhuVucChanging(string value);
    partial void OnQL_KhuVucChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public QuanLy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int QL_ID
		{
			get
			{
				return this._QL_ID;
			}
			set
			{
				if ((this._QL_ID != value))
				{
					this.OnQL_IDChanging(value);
					this.SendPropertyChanging();
					this._QL_ID = value;
					this.SendPropertyChanged("QL_ID");
					this.OnQL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_TenTruyCap", DbType="VarChar(20)")]
		public string QL_TenTruyCap
		{
			get
			{
				return this._QL_TenTruyCap;
			}
			set
			{
				if ((this._QL_TenTruyCap != value))
				{
					this.OnQL_TenTruyCapChanging(value);
					this.SendPropertyChanging();
					this._QL_TenTruyCap = value;
					this.SendPropertyChanged("QL_TenTruyCap");
					this.OnQL_TenTruyCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_Email", DbType="NVarChar(100)")]
		public string QL_Email
		{
			get
			{
				return this._QL_Email;
			}
			set
			{
				if ((this._QL_Email != value))
				{
					this.OnQL_EmailChanging(value);
					this.SendPropertyChanging();
					this._QL_Email = value;
					this.SendPropertyChanged("QL_Email");
					this.OnQL_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_MatKhau", DbType="VarChar(250)")]
		public string QL_MatKhau
		{
			get
			{
				return this._QL_MatKhau;
			}
			set
			{
				if ((this._QL_MatKhau != value))
				{
					this.OnQL_MatKhauChanging(value);
					this.SendPropertyChanging();
					this._QL_MatKhau = value;
					this.SendPropertyChanged("QL_MatKhau");
					this.OnQL_MatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_NgayBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> QL_NgayBatDau
		{
			get
			{
				return this._QL_NgayBatDau;
			}
			set
			{
				if ((this._QL_NgayBatDau != value))
				{
					this.OnQL_NgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._QL_NgayBatDau = value;
					this.SendPropertyChanged("QL_NgayBatDau");
					this.OnQL_NgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_Hoten", DbType="NVarChar(100)")]
		public string QL_Hoten
		{
			get
			{
				return this._QL_Hoten;
			}
			set
			{
				if ((this._QL_Hoten != value))
				{
					this.OnQL_HotenChanging(value);
					this.SendPropertyChanging();
					this._QL_Hoten = value;
					this.SendPropertyChanged("QL_Hoten");
					this.OnQL_HotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_CCCD", DbType="VarChar(50)")]
		public string QL_CCCD
		{
			get
			{
				return this._QL_CCCD;
			}
			set
			{
				if ((this._QL_CCCD != value))
				{
					this.OnQL_CCCDChanging(value);
					this.SendPropertyChanging();
					this._QL_CCCD = value;
					this.SendPropertyChanged("QL_CCCD");
					this.OnQL_CCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> QL_NgaySinh
		{
			get
			{
				return this._QL_NgaySinh;
			}
			set
			{
				if ((this._QL_NgaySinh != value))
				{
					this.OnQL_NgaySinhChanging(value);
					this.SendPropertyChanging();
					this._QL_NgaySinh = value;
					this.SendPropertyChanged("QL_NgaySinh");
					this.OnQL_NgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_GioiTinh", DbType="Int")]
		public System.Nullable<int> QL_GioiTinh
		{
			get
			{
				return this._QL_GioiTinh;
			}
			set
			{
				if ((this._QL_GioiTinh != value))
				{
					this.OnQL_GioiTinhChanging(value);
					this.SendPropertyChanging();
					this._QL_GioiTinh = value;
					this.SendPropertyChanged("QL_GioiTinh");
					this.OnQL_GioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_DiaChi", DbType="NVarChar(200)")]
		public string QL_DiaChi
		{
			get
			{
				return this._QL_DiaChi;
			}
			set
			{
				if ((this._QL_DiaChi != value))
				{
					this.OnQL_DiaChiChanging(value);
					this.SendPropertyChanging();
					this._QL_DiaChi = value;
					this.SendPropertyChanged("QL_DiaChi");
					this.OnQL_DiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_DienThoai", DbType="VarChar(100)")]
		public string QL_DienThoai
		{
			get
			{
				return this._QL_DienThoai;
			}
			set
			{
				if ((this._QL_DienThoai != value))
				{
					this.OnQL_DienThoaiChanging(value);
					this.SendPropertyChanging();
					this._QL_DienThoai = value;
					this.SendPropertyChanged("QL_DienThoai");
					this.OnQL_DienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_Quyen", DbType="TinyInt")]
		public System.Nullable<byte> QL_Quyen
		{
			get
			{
				return this._QL_Quyen;
			}
			set
			{
				if ((this._QL_Quyen != value))
				{
					this.OnQL_QuyenChanging(value);
					this.SendPropertyChanging();
					this._QL_Quyen = value;
					this.SendPropertyChanged("QL_Quyen");
					this.OnQL_QuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_TrangThai", DbType="Bit")]
		public System.Nullable<bool> QL_TrangThai
		{
			get
			{
				return this._QL_TrangThai;
			}
			set
			{
				if ((this._QL_TrangThai != value))
				{
					this.OnQL_TrangThaiChanging(value);
					this.SendPropertyChanging();
					this._QL_TrangThai = value;
					this.SendPropertyChanged("QL_TrangThai");
					this.OnQL_TrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QL_KhuVuc", DbType="VarChar(20)")]
		public string QL_KhuVuc
		{
			get
			{
				return this._QL_KhuVuc;
			}
			set
			{
				if ((this._QL_KhuVuc != value))
				{
					this.OnQL_KhuVucChanging(value);
					this.SendPropertyChanging();
					this._QL_KhuVuc = value;
					this.SendPropertyChanged("QL_KhuVuc");
					this.OnQL_KhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Users.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KH_ID;
		
		private string _KH_TenTruyCap;
		
		private string _KH_MatKhau;
		
		private string _KH_HoTen;
		
		private string _KH_Email;
		
		private System.Nullable<System.DateTime> _KH_NgayBatDau;
		
		private System.Nullable<bool> _KH_TrangThai;
		
		private string _KH_DienThoai;
		
		private string _KH_DiaChi;
		
		private string _KH_KhuVuc;
		
		private System.Guid _rowguid;
		
		private EntitySet<DonHang> _DonHangs;
		
		private EntitySet<DanhGiaSach> _DanhGiaSaches;
		
		private EntitySet<GioHang> _GioHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKH_IDChanging(int value);
    partial void OnKH_IDChanged();
    partial void OnKH_TenTruyCapChanging(string value);
    partial void OnKH_TenTruyCapChanged();
    partial void OnKH_MatKhauChanging(string value);
    partial void OnKH_MatKhauChanged();
    partial void OnKH_HoTenChanging(string value);
    partial void OnKH_HoTenChanged();
    partial void OnKH_EmailChanging(string value);
    partial void OnKH_EmailChanged();
    partial void OnKH_NgayBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnKH_NgayBatDauChanged();
    partial void OnKH_TrangThaiChanging(System.Nullable<bool> value);
    partial void OnKH_TrangThaiChanged();
    partial void OnKH_DienThoaiChanging(string value);
    partial void OnKH_DienThoaiChanged();
    partial void OnKH_DiaChiChanging(string value);
    partial void OnKH_DiaChiChanged();
    partial void OnKH_KhuVucChanging(string value);
    partial void OnKH_KhuVucChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public KhachHang()
		{
			this._DonHangs = new EntitySet<DonHang>(new Action<DonHang>(this.attach_DonHangs), new Action<DonHang>(this.detach_DonHangs));
			this._DanhGiaSaches = new EntitySet<DanhGiaSach>(new Action<DanhGiaSach>(this.attach_DanhGiaSaches), new Action<DanhGiaSach>(this.detach_DanhGiaSaches));
			this._GioHangs = new EntitySet<GioHang>(new Action<GioHang>(this.attach_GioHangs), new Action<GioHang>(this.detach_GioHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KH_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int KH_ID
		{
			get
			{
				return this._KH_ID;
			}
			set
			{
				if ((this._KH_ID != value))
				{
					this.OnKH_IDChanging(value);
					this.SendPropertyChanging();
					this._KH_ID = value;
					this.SendPropertyChanged("KH_ID");
					this.OnKH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KH_TenTruyCap", DbType="VarChar(50)")]
		public string KH_TenTruyCap
		{
			get
			{
				return this._KH_TenTruyCap;
			}
			set
			{
				if ((this._KH_TenTruyCap != value))
				{
					this.OnKH_TenTruyCapChanging(value);
					this.SendPropertyChanging();
					this._KH_TenTruyCap = value;
					this.SendPropertyChanged("KH_TenTruyCap");
					this.OnKH_TenTruyCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KH_MatKhau", DbType="VarChar(20)")]
		public string KH_MatKhau
		{
			get
			{
				return this._KH_MatKhau;
			}
			set
			{
				if ((this._KH_MatKhau != value))
				{
					this.OnKH_MatKhauChanging(value);
					this.SendPropertyChanging();
					this._KH_MatKhau = value;
					this.SendPropertyChanged("KH_MatKhau");
					this.OnKH_MatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KH_HoTen", DbType="NVarChar(50)")]
		public string KH_HoTen
		{
			get
			{
				return this._KH_HoTen;
			}
			set
			{
				if ((this._KH_HoTen != value))
				{
					this.OnKH_HoTenChanging(value);
					this.SendPropertyChanging();
					this._KH_HoTen = value;
					this.SendPropertyChanged("KH_HoTen");
					this.OnKH_HoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KH_Email", DbType="NVarChar(100)")]
		public string KH_Email
		{
			get
			{
				return this._KH_Email;
			}
			set
			{
				if ((this._KH_Email != value))
				{
					this.OnKH_EmailChanging(value);
					this.SendPropertyChanging();
					this._KH_Email = value;
					this.SendPropertyChanged("KH_Email");
					this.OnKH_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KH_NgayBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> KH_NgayBatDau
		{
			get
			{
				return this._KH_NgayBatDau;
			}
			set
			{
				if ((this._KH_NgayBatDau != value))
				{
					this.OnKH_NgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._KH_NgayBatDau = value;
					this.SendPropertyChanged("KH_NgayBatDau");
					this.OnKH_NgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KH_TrangThai", DbType="Bit")]
		public System.Nullable<bool> KH_TrangThai
		{
			get
			{
				return this._KH_TrangThai;
			}
			set
			{
				if ((this._KH_TrangThai != value))
				{
					this.OnKH_TrangThaiChanging(value);
					this.SendPropertyChanging();
					this._KH_TrangThai = value;
					this.SendPropertyChanged("KH_TrangThai");
					this.OnKH_TrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KH_DienThoai", DbType="VarChar(20)")]
		public string KH_DienThoai
		{
			get
			{
				return this._KH_DienThoai;
			}
			set
			{
				if ((this._KH_DienThoai != value))
				{
					this.OnKH_DienThoaiChanging(value);
					this.SendPropertyChanging();
					this._KH_DienThoai = value;
					this.SendPropertyChanged("KH_DienThoai");
					this.OnKH_DienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KH_DiaChi", DbType="NVarChar(250)")]
		public string KH_DiaChi
		{
			get
			{
				return this._KH_DiaChi;
			}
			set
			{
				if ((this._KH_DiaChi != value))
				{
					this.OnKH_DiaChiChanging(value);
					this.SendPropertyChanging();
					this._KH_DiaChi = value;
					this.SendPropertyChanged("KH_DiaChi");
					this.OnKH_DiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KH_KhuVuc", DbType="NVarChar(50)")]
		public string KH_KhuVuc
		{
			get
			{
				return this._KH_KhuVuc;
			}
			set
			{
				if ((this._KH_KhuVuc != value))
				{
					this.OnKH_KhuVucChanging(value);
					this.SendPropertyChanging();
					this._KH_KhuVuc = value;
					this.SendPropertyChanged("KH_KhuVuc");
					this.OnKH_KhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonHang", Storage="_DonHangs", ThisKey="KH_ID", OtherKey="DH_KhachHangId")]
		public EntitySet<DonHang> DonHangs
		{
			get
			{
				return this._DonHangs;
			}
			set
			{
				this._DonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DanhGiaSach", Storage="_DanhGiaSaches", ThisKey="KH_ID", OtherKey="DGS_KhachHangID")]
		public EntitySet<DanhGiaSach> DanhGiaSaches
		{
			get
			{
				return this._DanhGiaSaches;
			}
			set
			{
				this._DanhGiaSaches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_GioHang", Storage="_GioHangs", ThisKey="KH_ID", OtherKey="GH_KhachHangID")]
		public EntitySet<GioHang> GioHangs
		{
			get
			{
				return this._GioHangs;
			}
			set
			{
				this._GioHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_DanhGiaSaches(DanhGiaSach entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DanhGiaSaches(DanhGiaSach entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_GioHangs(GioHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_GioHangs(GioHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Orders.DanhGiaSach")]
	public partial class DanhGiaSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DGS_ID;
		
		private System.Nullable<int> _DGS_KhachHangID;
		
		private System.Nullable<int> _DGS_SachID;
		
		private string _DSG_NoiDung;
		
		private System.Guid _rowguid;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDGS_IDChanging(int value);
    partial void OnDGS_IDChanged();
    partial void OnDGS_KhachHangIDChanging(System.Nullable<int> value);
    partial void OnDGS_KhachHangIDChanged();
    partial void OnDGS_SachIDChanging(System.Nullable<int> value);
    partial void OnDGS_SachIDChanged();
    partial void OnDSG_NoiDungChanging(string value);
    partial void OnDSG_NoiDungChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public DanhGiaSach()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DGS_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DGS_ID
		{
			get
			{
				return this._DGS_ID;
			}
			set
			{
				if ((this._DGS_ID != value))
				{
					this.OnDGS_IDChanging(value);
					this.SendPropertyChanging();
					this._DGS_ID = value;
					this.SendPropertyChanged("DGS_ID");
					this.OnDGS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DGS_KhachHangID", DbType="Int")]
		public System.Nullable<int> DGS_KhachHangID
		{
			get
			{
				return this._DGS_KhachHangID;
			}
			set
			{
				if ((this._DGS_KhachHangID != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDGS_KhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._DGS_KhachHangID = value;
					this.SendPropertyChanged("DGS_KhachHangID");
					this.OnDGS_KhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DGS_SachID", DbType="Int")]
		public System.Nullable<int> DGS_SachID
		{
			get
			{
				return this._DGS_SachID;
			}
			set
			{
				if ((this._DGS_SachID != value))
				{
					this.OnDGS_SachIDChanging(value);
					this.SendPropertyChanging();
					this._DGS_SachID = value;
					this.SendPropertyChanged("DGS_SachID");
					this.OnDGS_SachIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSG_NoiDung", DbType="NVarChar(200)")]
		public string DSG_NoiDung
		{
			get
			{
				return this._DSG_NoiDung;
			}
			set
			{
				if ((this._DSG_NoiDung != value))
				{
					this.OnDSG_NoiDungChanging(value);
					this.SendPropertyChanging();
					this._DSG_NoiDung = value;
					this.SendPropertyChanged("DSG_NoiDung");
					this.OnDSG_NoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DanhGiaSach", Storage="_KhachHang", ThisKey="DGS_KhachHangID", OtherKey="KH_ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DanhGiaSaches.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DanhGiaSaches.Add(this);
						this._DGS_KhachHangID = value.KH_ID;
					}
					else
					{
						this._DGS_KhachHangID = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Orders.GioHang")]
	public partial class GioHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GH_ID;
		
		private System.Nullable<int> _GH_KhachHangID;
		
		private System.Nullable<int> _GH_SachID;
		
		private System.Nullable<int> _GH_SoLuong;
		
		private System.Nullable<decimal> _GH_ThanhTien;
		
		private System.Guid _rowguid;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGH_IDChanging(int value);
    partial void OnGH_IDChanged();
    partial void OnGH_KhachHangIDChanging(System.Nullable<int> value);
    partial void OnGH_KhachHangIDChanged();
    partial void OnGH_SachIDChanging(System.Nullable<int> value);
    partial void OnGH_SachIDChanged();
    partial void OnGH_SoLuongChanging(System.Nullable<int> value);
    partial void OnGH_SoLuongChanged();
    partial void OnGH_ThanhTienChanging(System.Nullable<decimal> value);
    partial void OnGH_ThanhTienChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public GioHang()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GH_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int GH_ID
		{
			get
			{
				return this._GH_ID;
			}
			set
			{
				if ((this._GH_ID != value))
				{
					this.OnGH_IDChanging(value);
					this.SendPropertyChanging();
					this._GH_ID = value;
					this.SendPropertyChanged("GH_ID");
					this.OnGH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GH_KhachHangID", DbType="Int")]
		public System.Nullable<int> GH_KhachHangID
		{
			get
			{
				return this._GH_KhachHangID;
			}
			set
			{
				if ((this._GH_KhachHangID != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGH_KhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._GH_KhachHangID = value;
					this.SendPropertyChanged("GH_KhachHangID");
					this.OnGH_KhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GH_SachID", DbType="Int")]
		public System.Nullable<int> GH_SachID
		{
			get
			{
				return this._GH_SachID;
			}
			set
			{
				if ((this._GH_SachID != value))
				{
					this.OnGH_SachIDChanging(value);
					this.SendPropertyChanging();
					this._GH_SachID = value;
					this.SendPropertyChanged("GH_SachID");
					this.OnGH_SachIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GH_SoLuong", DbType="Int")]
		public System.Nullable<int> GH_SoLuong
		{
			get
			{
				return this._GH_SoLuong;
			}
			set
			{
				if ((this._GH_SoLuong != value))
				{
					this.OnGH_SoLuongChanging(value);
					this.SendPropertyChanging();
					this._GH_SoLuong = value;
					this.SendPropertyChanged("GH_SoLuong");
					this.OnGH_SoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GH_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> GH_ThanhTien
		{
			get
			{
				return this._GH_ThanhTien;
			}
			set
			{
				if ((this._GH_ThanhTien != value))
				{
					this.OnGH_ThanhTienChanging(value);
					this.SendPropertyChanging();
					this._GH_ThanhTien = value;
					this.SendPropertyChanged("GH_ThanhTien");
					this.OnGH_ThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_GioHang", Storage="_KhachHang", ThisKey="GH_KhachHangID", OtherKey="KH_ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.GioHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.GioHangs.Add(this);
						this._GH_KhachHangID = value.KH_ID;
					}
					else
					{
						this._GH_KhachHangID = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Management.PhieuXuat")]
	public partial class PhieuXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PX_ID;
		
		private System.Nullable<System.DateTime> _PX_NgayXuat;
		
		private System.Nullable<int> _PX_DonHangID;
		
		private System.Guid _rowguid;
		
		private EntitySet<ChiTietPhieuXuat> _ChiTietPhieuXuats;
		
		private EntityRef<DonHang> _DonHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPX_IDChanging(int value);
    partial void OnPX_IDChanged();
    partial void OnPX_NgayXuatChanging(System.Nullable<System.DateTime> value);
    partial void OnPX_NgayXuatChanged();
    partial void OnPX_DonHangIDChanging(System.Nullable<int> value);
    partial void OnPX_DonHangIDChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public PhieuXuat()
		{
			this._ChiTietPhieuXuats = new EntitySet<ChiTietPhieuXuat>(new Action<ChiTietPhieuXuat>(this.attach_ChiTietPhieuXuats), new Action<ChiTietPhieuXuat>(this.detach_ChiTietPhieuXuats));
			this._DonHang = default(EntityRef<DonHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PX_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PX_ID
		{
			get
			{
				return this._PX_ID;
			}
			set
			{
				if ((this._PX_ID != value))
				{
					if (this._DonHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPX_IDChanging(value);
					this.SendPropertyChanging();
					this._PX_ID = value;
					this.SendPropertyChanged("PX_ID");
					this.OnPX_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PX_NgayXuat", DbType="DateTime")]
		public System.Nullable<System.DateTime> PX_NgayXuat
		{
			get
			{
				return this._PX_NgayXuat;
			}
			set
			{
				if ((this._PX_NgayXuat != value))
				{
					this.OnPX_NgayXuatChanging(value);
					this.SendPropertyChanging();
					this._PX_NgayXuat = value;
					this.SendPropertyChanged("PX_NgayXuat");
					this.OnPX_NgayXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PX_DonHangID", DbType="Int")]
		public System.Nullable<int> PX_DonHangID
		{
			get
			{
				return this._PX_DonHangID;
			}
			set
			{
				if ((this._PX_DonHangID != value))
				{
					this.OnPX_DonHangIDChanging(value);
					this.SendPropertyChanging();
					this._PX_DonHangID = value;
					this.SendPropertyChanged("PX_DonHangID");
					this.OnPX_DonHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuXuat_ChiTietPhieuXuat", Storage="_ChiTietPhieuXuats", ThisKey="PX_ID", OtherKey="CTPX_PhieuXuatID")]
		public EntitySet<ChiTietPhieuXuat> ChiTietPhieuXuats
		{
			get
			{
				return this._ChiTietPhieuXuats;
			}
			set
			{
				this._ChiTietPhieuXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonHang_PhieuXuat", Storage="_DonHang", ThisKey="PX_ID", OtherKey="DH_ID", IsForeignKey=true)]
		public DonHang DonHang
		{
			get
			{
				return this._DonHang.Entity;
			}
			set
			{
				DonHang previousValue = this._DonHang.Entity;
				if (((previousValue != value) 
							|| (this._DonHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonHang.Entity = null;
						previousValue.PhieuXuat = null;
					}
					this._DonHang.Entity = value;
					if ((value != null))
					{
						value.PhieuXuat = this;
						this._PX_ID = value.DH_ID;
					}
					else
					{
						this._PX_ID = default(int);
					}
					this.SendPropertyChanged("DonHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuXuats(ChiTietPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.PhieuXuat = this;
		}
		
		private void detach_ChiTietPhieuXuats(ChiTietPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.PhieuXuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Management.ChiTietPhieuXuat")]
	public partial class ChiTietPhieuXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CTPX_ID;
		
		private System.Nullable<int> _CTPX_PhieuXuatID;
		
		private System.Nullable<int> _CTPX_SachID;
		
		private System.Nullable<int> _CTPX_SoLuong;
		
		private System.Nullable<decimal> _CTPX_ThanhTien;
		
		private System.Guid _rowguid;
		
		private EntityRef<PhieuXuat> _PhieuXuat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCTPX_IDChanging(int value);
    partial void OnCTPX_IDChanged();
    partial void OnCTPX_PhieuXuatIDChanging(System.Nullable<int> value);
    partial void OnCTPX_PhieuXuatIDChanged();
    partial void OnCTPX_SachIDChanging(System.Nullable<int> value);
    partial void OnCTPX_SachIDChanged();
    partial void OnCTPX_SoLuongChanging(System.Nullable<int> value);
    partial void OnCTPX_SoLuongChanged();
    partial void OnCTPX_ThanhTienChanging(System.Nullable<decimal> value);
    partial void OnCTPX_ThanhTienChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public ChiTietPhieuXuat()
		{
			this._PhieuXuat = default(EntityRef<PhieuXuat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTPX_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CTPX_ID
		{
			get
			{
				return this._CTPX_ID;
			}
			set
			{
				if ((this._CTPX_ID != value))
				{
					this.OnCTPX_IDChanging(value);
					this.SendPropertyChanging();
					this._CTPX_ID = value;
					this.SendPropertyChanged("CTPX_ID");
					this.OnCTPX_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTPX_PhieuXuatID", DbType="Int")]
		public System.Nullable<int> CTPX_PhieuXuatID
		{
			get
			{
				return this._CTPX_PhieuXuatID;
			}
			set
			{
				if ((this._CTPX_PhieuXuatID != value))
				{
					if (this._PhieuXuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCTPX_PhieuXuatIDChanging(value);
					this.SendPropertyChanging();
					this._CTPX_PhieuXuatID = value;
					this.SendPropertyChanged("CTPX_PhieuXuatID");
					this.OnCTPX_PhieuXuatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTPX_SachID", DbType="Int")]
		public System.Nullable<int> CTPX_SachID
		{
			get
			{
				return this._CTPX_SachID;
			}
			set
			{
				if ((this._CTPX_SachID != value))
				{
					this.OnCTPX_SachIDChanging(value);
					this.SendPropertyChanging();
					this._CTPX_SachID = value;
					this.SendPropertyChanged("CTPX_SachID");
					this.OnCTPX_SachIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTPX_SoLuong", DbType="Int")]
		public System.Nullable<int> CTPX_SoLuong
		{
			get
			{
				return this._CTPX_SoLuong;
			}
			set
			{
				if ((this._CTPX_SoLuong != value))
				{
					this.OnCTPX_SoLuongChanging(value);
					this.SendPropertyChanging();
					this._CTPX_SoLuong = value;
					this.SendPropertyChanged("CTPX_SoLuong");
					this.OnCTPX_SoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTPX_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> CTPX_ThanhTien
		{
			get
			{
				return this._CTPX_ThanhTien;
			}
			set
			{
				if ((this._CTPX_ThanhTien != value))
				{
					this.OnCTPX_ThanhTienChanging(value);
					this.SendPropertyChanging();
					this._CTPX_ThanhTien = value;
					this.SendPropertyChanged("CTPX_ThanhTien");
					this.OnCTPX_ThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuXuat_ChiTietPhieuXuat", Storage="_PhieuXuat", ThisKey="CTPX_PhieuXuatID", OtherKey="PX_ID", IsForeignKey=true)]
		public PhieuXuat PhieuXuat
		{
			get
			{
				return this._PhieuXuat.Entity;
			}
			set
			{
				PhieuXuat previousValue = this._PhieuXuat.Entity;
				if (((previousValue != value) 
							|| (this._PhieuXuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuXuat.Entity = null;
						previousValue.ChiTietPhieuXuats.Remove(this);
					}
					this._PhieuXuat.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuXuats.Add(this);
						this._CTPX_PhieuXuatID = value.PX_ID;
					}
					else
					{
						this._CTPX_PhieuXuatID = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhieuXuat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
