#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_SQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Nhom_Solo")]
	public partial class NhaXuatBanClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNhaXuatBan(NhaXuatBan instance);
    partial void UpdateNhaXuatBan(NhaXuatBan instance);
    partial void DeleteNhaXuatBan(NhaXuatBan instance);
    partial void InsertSach(Sach instance);
    partial void UpdateSach(Sach instance);
    partial void DeleteSach(Sach instance);
    partial void InsertTheLoaiSach(TheLoaiSach instance);
    partial void UpdateTheLoaiSach(TheLoaiSach instance);
    partial void DeleteTheLoaiSach(TheLoaiSach instance);
    partial void InsertTacGia(TacGia instance);
    partial void UpdateTacGia(TacGia instance);
    partial void DeleteTacGia(TacGia instance);
    partial void InsertChiTietPhieuNhap(ChiTietPhieuNhap instance);
    partial void UpdateChiTietPhieuNhap(ChiTietPhieuNhap instance);
    partial void DeleteChiTietPhieuNhap(ChiTietPhieuNhap instance);
    partial void InsertNgonNgu(NgonNgu instance);
    partial void UpdateNgonNgu(NgonNgu instance);
    partial void DeleteNgonNgu(NgonNgu instance);
    partial void InsertNhaCungCap(NhaCungCap instance);
    partial void UpdateNhaCungCap(NhaCungCap instance);
    partial void DeleteNhaCungCap(NhaCungCap instance);
    partial void InsertPhieuNhap(PhieuNhap instance);
    partial void UpdatePhieuNhap(PhieuNhap instance);
    partial void DeletePhieuNhap(PhieuNhap instance);
    #endregion
		
		public NhaXuatBanClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NhaXuatBanClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NhaXuatBanClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NhaXuatBanClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NhaXuatBan> NhaXuatBans
		{
			get
			{
				return this.GetTable<NhaXuatBan>();
			}
		}
		
		public System.Data.Linq.Table<Sach> Saches
		{
			get
			{
				return this.GetTable<Sach>();
			}
		}
		
		public System.Data.Linq.Table<TheLoaiSach> TheLoaiSaches
		{
			get
			{
				return this.GetTable<TheLoaiSach>();
			}
		}
		
		public System.Data.Linq.Table<TacGia> TacGias
		{
			get
			{
				return this.GetTable<TacGia>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietPhieuNhap> ChiTietPhieuNhaps
		{
			get
			{
				return this.GetTable<ChiTietPhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<NgonNgu> NgonNgus
		{
			get
			{
				return this.GetTable<NgonNgu>();
			}
		}
		
		public System.Data.Linq.Table<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this.GetTable<NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<PhieuNhap> PhieuNhaps
		{
			get
			{
				return this.GetTable<PhieuNhap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Book.NhaXuatBan")]
	public partial class NhaXuatBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NXB_ID;
		
		private string _NXB_Ten;
		
		private System.Guid _rowguid;
		
		private EntitySet<Sach> _Saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNXB_IDChanging(int value);
    partial void OnNXB_IDChanged();
    partial void OnNXB_TenChanging(string value);
    partial void OnNXB_TenChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public NhaXuatBan()
		{
			this._Saches = new EntitySet<Sach>(new Action<Sach>(this.attach_Saches), new Action<Sach>(this.detach_Saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NXB_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int NXB_ID
		{
			get
			{
				return this._NXB_ID;
			}
			set
			{
				if ((this._NXB_ID != value))
				{
					this.OnNXB_IDChanging(value);
					this.SendPropertyChanging();
					this._NXB_ID = value;
					this.SendPropertyChanged("NXB_ID");
					this.OnNXB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NXB_Ten", DbType="NVarChar(100)")]
		public string NXB_Ten
		{
			get
			{
				return this._NXB_Ten;
			}
			set
			{
				if ((this._NXB_Ten != value))
				{
					this.OnNXB_TenChanging(value);
					this.SendPropertyChanging();
					this._NXB_Ten = value;
					this.SendPropertyChanged("NXB_Ten");
					this.OnNXB_TenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaXuatBan_Sach", Storage="_Saches", ThisKey="NXB_ID", OtherKey="S_NXBID")]
		public EntitySet<Sach> Saches
		{
			get
			{
				return this._Saches;
			}
			set
			{
				this._Saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.NhaXuatBan = this;
		}
		
		private void detach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.NhaXuatBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Book.Sach")]
	public partial class Sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _S_ID;
		
		private System.Nullable<int> _S_TheLoaiID;
		
		private string _S_Ten;
		
		private string _S_Mota;
		
		private string _S_TuKhoa;
		
		private System.Nullable<decimal> _S_GiaBan;
		
		private System.Nullable<bool> _S_TrangThai;
		
		private System.Nullable<int> _S_SoLanXem;
		
		private string _S_KhoSach;
		
		private System.Nullable<int> _S_NXBID;
		
		private System.Nullable<int> _S_NamXuatBan;
		
		private System.Nullable<decimal> _S_GiaNhap;
		
		private System.Nullable<int> _S_SoLuong;
		
		private System.Nullable<int> _S_SoTrang;
		
		private System.Nullable<int> _S_TacGiaId;
		
		private System.Nullable<int> _S_TrongLuong;
		
		private System.Nullable<int> _S_NgonNguID;
		
		private System.Nullable<int> _S_NhaCungCapID;
		
		private System.Guid _rowguid;
		
		private EntitySet<ChiTietPhieuNhap> _ChiTietPhieuNhaps;
		
		private EntityRef<NhaXuatBan> _NhaXuatBan;
		
		private EntityRef<TheLoaiSach> _TheLoaiSach;
		
		private EntityRef<TacGia> _TacGia;
		
		private EntityRef<NgonNgu> _NgonNgu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnS_IDChanging(int value);
    partial void OnS_IDChanged();
    partial void OnS_TheLoaiIDChanging(System.Nullable<int> value);
    partial void OnS_TheLoaiIDChanged();
    partial void OnS_TenChanging(string value);
    partial void OnS_TenChanged();
    partial void OnS_MotaChanging(string value);
    partial void OnS_MotaChanged();
    partial void OnS_TuKhoaChanging(string value);
    partial void OnS_TuKhoaChanged();
    partial void OnS_GiaBanChanging(System.Nullable<decimal> value);
    partial void OnS_GiaBanChanged();
    partial void OnS_TrangThaiChanging(System.Nullable<bool> value);
    partial void OnS_TrangThaiChanged();
    partial void OnS_SoLanXemChanging(System.Nullable<int> value);
    partial void OnS_SoLanXemChanged();
    partial void OnS_KhoSachChanging(string value);
    partial void OnS_KhoSachChanged();
    partial void OnS_NXBIDChanging(System.Nullable<int> value);
    partial void OnS_NXBIDChanged();
    partial void OnS_NamXuatBanChanging(System.Nullable<int> value);
    partial void OnS_NamXuatBanChanged();
    partial void OnS_GiaNhapChanging(System.Nullable<decimal> value);
    partial void OnS_GiaNhapChanged();
    partial void OnS_SoLuongChanging(System.Nullable<int> value);
    partial void OnS_SoLuongChanged();
    partial void OnS_SoTrangChanging(System.Nullable<int> value);
    partial void OnS_SoTrangChanged();
    partial void OnS_TacGiaIdChanging(System.Nullable<int> value);
    partial void OnS_TacGiaIdChanged();
    partial void OnS_TrongLuongChanging(System.Nullable<int> value);
    partial void OnS_TrongLuongChanged();
    partial void OnS_NgonNguIDChanging(System.Nullable<int> value);
    partial void OnS_NgonNguIDChanged();
    partial void OnS_NhaCungCapIDChanging(System.Nullable<int> value);
    partial void OnS_NhaCungCapIDChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public Sach()
		{
			this._ChiTietPhieuNhaps = new EntitySet<ChiTietPhieuNhap>(new Action<ChiTietPhieuNhap>(this.attach_ChiTietPhieuNhaps), new Action<ChiTietPhieuNhap>(this.detach_ChiTietPhieuNhaps));
			this._NhaXuatBan = default(EntityRef<NhaXuatBan>);
			this._TheLoaiSach = default(EntityRef<TheLoaiSach>);
			this._TacGia = default(EntityRef<TacGia>);
			this._NgonNgu = default(EntityRef<NgonNgu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this.OnS_IDChanging(value);
					this.SendPropertyChanging();
					this._S_ID = value;
					this.SendPropertyChanged("S_ID");
					this.OnS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_TheLoaiID", DbType="Int")]
		public System.Nullable<int> S_TheLoaiID
		{
			get
			{
				return this._S_TheLoaiID;
			}
			set
			{
				if ((this._S_TheLoaiID != value))
				{
					if (this._TheLoaiSach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnS_TheLoaiIDChanging(value);
					this.SendPropertyChanging();
					this._S_TheLoaiID = value;
					this.SendPropertyChanged("S_TheLoaiID");
					this.OnS_TheLoaiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Ten", DbType="NVarChar(200)")]
		public string S_Ten
		{
			get
			{
				return this._S_Ten;
			}
			set
			{
				if ((this._S_Ten != value))
				{
					this.OnS_TenChanging(value);
					this.SendPropertyChanging();
					this._S_Ten = value;
					this.SendPropertyChanged("S_Ten");
					this.OnS_TenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Mota", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string S_Mota
		{
			get
			{
				return this._S_Mota;
			}
			set
			{
				if ((this._S_Mota != value))
				{
					this.OnS_MotaChanging(value);
					this.SendPropertyChanging();
					this._S_Mota = value;
					this.SendPropertyChanged("S_Mota");
					this.OnS_MotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_TuKhoa", DbType="NVarChar(500)")]
		public string S_TuKhoa
		{
			get
			{
				return this._S_TuKhoa;
			}
			set
			{
				if ((this._S_TuKhoa != value))
				{
					this.OnS_TuKhoaChanging(value);
					this.SendPropertyChanging();
					this._S_TuKhoa = value;
					this.SendPropertyChanged("S_TuKhoa");
					this.OnS_TuKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_GiaBan", DbType="Money")]
		public System.Nullable<decimal> S_GiaBan
		{
			get
			{
				return this._S_GiaBan;
			}
			set
			{
				if ((this._S_GiaBan != value))
				{
					this.OnS_GiaBanChanging(value);
					this.SendPropertyChanging();
					this._S_GiaBan = value;
					this.SendPropertyChanged("S_GiaBan");
					this.OnS_GiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_TrangThai", DbType="Bit")]
		public System.Nullable<bool> S_TrangThai
		{
			get
			{
				return this._S_TrangThai;
			}
			set
			{
				if ((this._S_TrangThai != value))
				{
					this.OnS_TrangThaiChanging(value);
					this.SendPropertyChanging();
					this._S_TrangThai = value;
					this.SendPropertyChanged("S_TrangThai");
					this.OnS_TrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_SoLanXem", DbType="Int")]
		public System.Nullable<int> S_SoLanXem
		{
			get
			{
				return this._S_SoLanXem;
			}
			set
			{
				if ((this._S_SoLanXem != value))
				{
					this.OnS_SoLanXemChanging(value);
					this.SendPropertyChanging();
					this._S_SoLanXem = value;
					this.SendPropertyChanged("S_SoLanXem");
					this.OnS_SoLanXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_KhoSach", DbType="VarChar(10)")]
		public string S_KhoSach
		{
			get
			{
				return this._S_KhoSach;
			}
			set
			{
				if ((this._S_KhoSach != value))
				{
					this.OnS_KhoSachChanging(value);
					this.SendPropertyChanging();
					this._S_KhoSach = value;
					this.SendPropertyChanged("S_KhoSach");
					this.OnS_KhoSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_NXBID", DbType="Int")]
		public System.Nullable<int> S_NXBID
		{
			get
			{
				return this._S_NXBID;
			}
			set
			{
				if ((this._S_NXBID != value))
				{
					if (this._NhaXuatBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnS_NXBIDChanging(value);
					this.SendPropertyChanging();
					this._S_NXBID = value;
					this.SendPropertyChanged("S_NXBID");
					this.OnS_NXBIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_NamXuatBan", DbType="Int")]
		public System.Nullable<int> S_NamXuatBan
		{
			get
			{
				return this._S_NamXuatBan;
			}
			set
			{
				if ((this._S_NamXuatBan != value))
				{
					this.OnS_NamXuatBanChanging(value);
					this.SendPropertyChanging();
					this._S_NamXuatBan = value;
					this.SendPropertyChanged("S_NamXuatBan");
					this.OnS_NamXuatBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_GiaNhap", DbType="Money")]
		public System.Nullable<decimal> S_GiaNhap
		{
			get
			{
				return this._S_GiaNhap;
			}
			set
			{
				if ((this._S_GiaNhap != value))
				{
					this.OnS_GiaNhapChanging(value);
					this.SendPropertyChanging();
					this._S_GiaNhap = value;
					this.SendPropertyChanged("S_GiaNhap");
					this.OnS_GiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_SoLuong", DbType="Int")]
		public System.Nullable<int> S_SoLuong
		{
			get
			{
				return this._S_SoLuong;
			}
			set
			{
				if ((this._S_SoLuong != value))
				{
					this.OnS_SoLuongChanging(value);
					this.SendPropertyChanging();
					this._S_SoLuong = value;
					this.SendPropertyChanged("S_SoLuong");
					this.OnS_SoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_SoTrang", DbType="Int")]
		public System.Nullable<int> S_SoTrang
		{
			get
			{
				return this._S_SoTrang;
			}
			set
			{
				if ((this._S_SoTrang != value))
				{
					this.OnS_SoTrangChanging(value);
					this.SendPropertyChanging();
					this._S_SoTrang = value;
					this.SendPropertyChanged("S_SoTrang");
					this.OnS_SoTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_TacGiaId", DbType="Int")]
		public System.Nullable<int> S_TacGiaId
		{
			get
			{
				return this._S_TacGiaId;
			}
			set
			{
				if ((this._S_TacGiaId != value))
				{
					if (this._TacGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnS_TacGiaIdChanging(value);
					this.SendPropertyChanging();
					this._S_TacGiaId = value;
					this.SendPropertyChanged("S_TacGiaId");
					this.OnS_TacGiaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_TrongLuong", DbType="Int")]
		public System.Nullable<int> S_TrongLuong
		{
			get
			{
				return this._S_TrongLuong;
			}
			set
			{
				if ((this._S_TrongLuong != value))
				{
					this.OnS_TrongLuongChanging(value);
					this.SendPropertyChanging();
					this._S_TrongLuong = value;
					this.SendPropertyChanged("S_TrongLuong");
					this.OnS_TrongLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_NgonNguID", DbType="Int")]
		public System.Nullable<int> S_NgonNguID
		{
			get
			{
				return this._S_NgonNguID;
			}
			set
			{
				if ((this._S_NgonNguID != value))
				{
					if (this._NgonNgu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnS_NgonNguIDChanging(value);
					this.SendPropertyChanging();
					this._S_NgonNguID = value;
					this.SendPropertyChanged("S_NgonNguID");
					this.OnS_NgonNguIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_NhaCungCapID", DbType="Int")]
		public System.Nullable<int> S_NhaCungCapID
		{
			get
			{
				return this._S_NhaCungCapID;
			}
			set
			{
				if ((this._S_NhaCungCapID != value))
				{
					this.OnS_NhaCungCapIDChanging(value);
					this.SendPropertyChanging();
					this._S_NhaCungCapID = value;
					this.SendPropertyChanged("S_NhaCungCapID");
					this.OnS_NhaCungCapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sach_ChiTietPhieuNhap", Storage="_ChiTietPhieuNhaps", ThisKey="S_ID", OtherKey="CTPN_SachID")]
		public EntitySet<ChiTietPhieuNhap> ChiTietPhieuNhaps
		{
			get
			{
				return this._ChiTietPhieuNhaps;
			}
			set
			{
				this._ChiTietPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaXuatBan_Sach", Storage="_NhaXuatBan", ThisKey="S_NXBID", OtherKey="NXB_ID", IsForeignKey=true)]
		public NhaXuatBan NhaXuatBan
		{
			get
			{
				return this._NhaXuatBan.Entity;
			}
			set
			{
				NhaXuatBan previousValue = this._NhaXuatBan.Entity;
				if (((previousValue != value) 
							|| (this._NhaXuatBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaXuatBan.Entity = null;
						previousValue.Saches.Remove(this);
					}
					this._NhaXuatBan.Entity = value;
					if ((value != null))
					{
						value.Saches.Add(this);
						this._S_NXBID = value.NXB_ID;
					}
					else
					{
						this._S_NXBID = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhaXuatBan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoaiSach_Sach", Storage="_TheLoaiSach", ThisKey="S_TheLoaiID", OtherKey="TL_ID", IsForeignKey=true)]
		public TheLoaiSach TheLoaiSach
		{
			get
			{
				return this._TheLoaiSach.Entity;
			}
			set
			{
				TheLoaiSach previousValue = this._TheLoaiSach.Entity;
				if (((previousValue != value) 
							|| (this._TheLoaiSach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheLoaiSach.Entity = null;
						previousValue.Saches.Remove(this);
					}
					this._TheLoaiSach.Entity = value;
					if ((value != null))
					{
						value.Saches.Add(this);
						this._S_TheLoaiID = value.TL_ID;
					}
					else
					{
						this._S_TheLoaiID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TheLoaiSach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TacGia_Sach", Storage="_TacGia", ThisKey="S_TacGiaId", OtherKey="TG_ID", IsForeignKey=true)]
		public TacGia TacGia
		{
			get
			{
				return this._TacGia.Entity;
			}
			set
			{
				TacGia previousValue = this._TacGia.Entity;
				if (((previousValue != value) 
							|| (this._TacGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TacGia.Entity = null;
						previousValue.Saches.Remove(this);
					}
					this._TacGia.Entity = value;
					if ((value != null))
					{
						value.Saches.Add(this);
						this._S_TacGiaId = value.TG_ID;
					}
					else
					{
						this._S_TacGiaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("TacGia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NgonNgu_Sach", Storage="_NgonNgu", ThisKey="S_NgonNguID", OtherKey="NN_ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public NgonNgu NgonNgu
		{
			get
			{
				return this._NgonNgu.Entity;
			}
			set
			{
				NgonNgu previousValue = this._NgonNgu.Entity;
				if (((previousValue != value) 
							|| (this._NgonNgu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NgonNgu.Entity = null;
						previousValue.Saches.Remove(this);
					}
					this._NgonNgu.Entity = value;
					if ((value != null))
					{
						value.Saches.Add(this);
						this._S_NgonNguID = value.NN_ID;
					}
					else
					{
						this._S_NgonNguID = default(Nullable<int>);
					}
					this.SendPropertyChanged("NgonNgu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuNhaps(ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.Sach = this;
		}
		
		private void detach_ChiTietPhieuNhaps(ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.Sach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Book.TheLoaiSach")]
	public partial class TheLoaiSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TL_ID;
		
		private string _TL_Ten;
		
		private System.Nullable<bool> _TL_TrangThai;
		
		private System.Guid _rowguid;
		
		private EntitySet<Sach> _Saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTL_IDChanging(int value);
    partial void OnTL_IDChanged();
    partial void OnTL_TenChanging(string value);
    partial void OnTL_TenChanged();
    partial void OnTL_TrangThaiChanging(System.Nullable<bool> value);
    partial void OnTL_TrangThaiChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public TheLoaiSach()
		{
			this._Saches = new EntitySet<Sach>(new Action<Sach>(this.attach_Saches), new Action<Sach>(this.detach_Saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TL_ID
		{
			get
			{
				return this._TL_ID;
			}
			set
			{
				if ((this._TL_ID != value))
				{
					this.OnTL_IDChanging(value);
					this.SendPropertyChanging();
					this._TL_ID = value;
					this.SendPropertyChanged("TL_ID");
					this.OnTL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_Ten", DbType="NVarChar(250)")]
		public string TL_Ten
		{
			get
			{
				return this._TL_Ten;
			}
			set
			{
				if ((this._TL_Ten != value))
				{
					this.OnTL_TenChanging(value);
					this.SendPropertyChanging();
					this._TL_Ten = value;
					this.SendPropertyChanged("TL_Ten");
					this.OnTL_TenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TL_TrangThai
		{
			get
			{
				return this._TL_TrangThai;
			}
			set
			{
				if ((this._TL_TrangThai != value))
				{
					this.OnTL_TrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TL_TrangThai = value;
					this.SendPropertyChanged("TL_TrangThai");
					this.OnTL_TrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoaiSach_Sach", Storage="_Saches", ThisKey="TL_ID", OtherKey="S_TheLoaiID")]
		public EntitySet<Sach> Saches
		{
			get
			{
				return this._Saches;
			}
			set
			{
				this._Saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.TheLoaiSach = this;
		}
		
		private void detach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.TheLoaiSach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Book.TacGia")]
	public partial class TacGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TG_ID;
		
		private string _TG_HoTen;
		
		private System.Nullable<System.DateTime> _TG_NgaySinh;
		
		private string _TG_QuocTich;
		
		private System.Guid _rowguid;
		
		private EntitySet<Sach> _Saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTG_IDChanging(int value);
    partial void OnTG_IDChanged();
    partial void OnTG_HoTenChanging(string value);
    partial void OnTG_HoTenChanged();
    partial void OnTG_NgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnTG_NgaySinhChanged();
    partial void OnTG_QuocTichChanging(string value);
    partial void OnTG_QuocTichChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public TacGia()
		{
			this._Saches = new EntitySet<Sach>(new Action<Sach>(this.attach_Saches), new Action<Sach>(this.detach_Saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TG_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TG_ID
		{
			get
			{
				return this._TG_ID;
			}
			set
			{
				if ((this._TG_ID != value))
				{
					this.OnTG_IDChanging(value);
					this.SendPropertyChanging();
					this._TG_ID = value;
					this.SendPropertyChanged("TG_ID");
					this.OnTG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TG_HoTen", DbType="NVarChar(100)")]
		public string TG_HoTen
		{
			get
			{
				return this._TG_HoTen;
			}
			set
			{
				if ((this._TG_HoTen != value))
				{
					this.OnTG_HoTenChanging(value);
					this.SendPropertyChanging();
					this._TG_HoTen = value;
					this.SendPropertyChanged("TG_HoTen");
					this.OnTG_HoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TG_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> TG_NgaySinh
		{
			get
			{
				return this._TG_NgaySinh;
			}
			set
			{
				if ((this._TG_NgaySinh != value))
				{
					this.OnTG_NgaySinhChanging(value);
					this.SendPropertyChanging();
					this._TG_NgaySinh = value;
					this.SendPropertyChanged("TG_NgaySinh");
					this.OnTG_NgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TG_QuocTich", DbType="NVarChar(50)")]
		public string TG_QuocTich
		{
			get
			{
				return this._TG_QuocTich;
			}
			set
			{
				if ((this._TG_QuocTich != value))
				{
					this.OnTG_QuocTichChanging(value);
					this.SendPropertyChanging();
					this._TG_QuocTich = value;
					this.SendPropertyChanged("TG_QuocTich");
					this.OnTG_QuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TacGia_Sach", Storage="_Saches", ThisKey="TG_ID", OtherKey="S_TacGiaId")]
		public EntitySet<Sach> Saches
		{
			get
			{
				return this._Saches;
			}
			set
			{
				this._Saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.TacGia = this;
		}
		
		private void detach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.TacGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Management.ChiTietPhieuNhap")]
	public partial class ChiTietPhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CTPN_ID;
		
		private System.Nullable<int> _CTPN_PhieuNhapID;
		
		private System.Nullable<int> _CTPN_SachID;
		
		private System.Nullable<int> _CTPN_SoLuong;
		
		private System.Nullable<decimal> _CTPN_ThanhTien;
		
		private System.Guid _rowguid;
		
		private EntityRef<Sach> _Sach;
		
		private EntityRef<PhieuNhap> _PhieuNhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCTPN_IDChanging(int value);
    partial void OnCTPN_IDChanged();
    partial void OnCTPN_PhieuNhapIDChanging(System.Nullable<int> value);
    partial void OnCTPN_PhieuNhapIDChanged();
    partial void OnCTPN_SachIDChanging(System.Nullable<int> value);
    partial void OnCTPN_SachIDChanged();
    partial void OnCTPN_SoLuongChanging(System.Nullable<int> value);
    partial void OnCTPN_SoLuongChanged();
    partial void OnCTPN_ThanhTienChanging(System.Nullable<decimal> value);
    partial void OnCTPN_ThanhTienChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public ChiTietPhieuNhap()
		{
			this._Sach = default(EntityRef<Sach>);
			this._PhieuNhap = default(EntityRef<PhieuNhap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTPN_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CTPN_ID
		{
			get
			{
				return this._CTPN_ID;
			}
			set
			{
				if ((this._CTPN_ID != value))
				{
					this.OnCTPN_IDChanging(value);
					this.SendPropertyChanging();
					this._CTPN_ID = value;
					this.SendPropertyChanged("CTPN_ID");
					this.OnCTPN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTPN_PhieuNhapID", DbType="Int")]
		public System.Nullable<int> CTPN_PhieuNhapID
		{
			get
			{
				return this._CTPN_PhieuNhapID;
			}
			set
			{
				if ((this._CTPN_PhieuNhapID != value))
				{
					if (this._PhieuNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCTPN_PhieuNhapIDChanging(value);
					this.SendPropertyChanging();
					this._CTPN_PhieuNhapID = value;
					this.SendPropertyChanged("CTPN_PhieuNhapID");
					this.OnCTPN_PhieuNhapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTPN_SachID", DbType="Int")]
		public System.Nullable<int> CTPN_SachID
		{
			get
			{
				return this._CTPN_SachID;
			}
			set
			{
				if ((this._CTPN_SachID != value))
				{
					if (this._Sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCTPN_SachIDChanging(value);
					this.SendPropertyChanging();
					this._CTPN_SachID = value;
					this.SendPropertyChanged("CTPN_SachID");
					this.OnCTPN_SachIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTPN_SoLuong", DbType="Int")]
		public System.Nullable<int> CTPN_SoLuong
		{
			get
			{
				return this._CTPN_SoLuong;
			}
			set
			{
				if ((this._CTPN_SoLuong != value))
				{
					this.OnCTPN_SoLuongChanging(value);
					this.SendPropertyChanging();
					this._CTPN_SoLuong = value;
					this.SendPropertyChanged("CTPN_SoLuong");
					this.OnCTPN_SoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTPN_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> CTPN_ThanhTien
		{
			get
			{
				return this._CTPN_ThanhTien;
			}
			set
			{
				if ((this._CTPN_ThanhTien != value))
				{
					this.OnCTPN_ThanhTienChanging(value);
					this.SendPropertyChanging();
					this._CTPN_ThanhTien = value;
					this.SendPropertyChanged("CTPN_ThanhTien");
					this.OnCTPN_ThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sach_ChiTietPhieuNhap", Storage="_Sach", ThisKey="CTPN_SachID", OtherKey="S_ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Sach Sach
		{
			get
			{
				return this._Sach.Entity;
			}
			set
			{
				Sach previousValue = this._Sach.Entity;
				if (((previousValue != value) 
							|| (this._Sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sach.Entity = null;
						previousValue.ChiTietPhieuNhaps.Remove(this);
					}
					this._Sach.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuNhaps.Add(this);
						this._CTPN_SachID = value.S_ID;
					}
					else
					{
						this._CTPN_SachID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Sach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhap_ChiTietPhieuNhap", Storage="_PhieuNhap", ThisKey="CTPN_PhieuNhapID", OtherKey="PN_ID", IsForeignKey=true, DeleteRule="CASCADE")]
		public PhieuNhap PhieuNhap
		{
			get
			{
				return this._PhieuNhap.Entity;
			}
			set
			{
				PhieuNhap previousValue = this._PhieuNhap.Entity;
				if (((previousValue != value) 
							|| (this._PhieuNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuNhap.Entity = null;
						previousValue.ChiTietPhieuNhaps.Remove(this);
					}
					this._PhieuNhap.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuNhaps.Add(this);
						this._CTPN_PhieuNhapID = value.PN_ID;
					}
					else
					{
						this._CTPN_PhieuNhapID = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhieuNhap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Management.NgonNgu")]
	public partial class NgonNgu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NN_ID;
		
		private string _NN_Ten;
		
		private System.Guid _rowguid;
		
		private EntitySet<Sach> _Saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNN_IDChanging(int value);
    partial void OnNN_IDChanged();
    partial void OnNN_TenChanging(string value);
    partial void OnNN_TenChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public NgonNgu()
		{
			this._Saches = new EntitySet<Sach>(new Action<Sach>(this.attach_Saches), new Action<Sach>(this.detach_Saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NN_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int NN_ID
		{
			get
			{
				return this._NN_ID;
			}
			set
			{
				if ((this._NN_ID != value))
				{
					this.OnNN_IDChanging(value);
					this.SendPropertyChanging();
					this._NN_ID = value;
					this.SendPropertyChanged("NN_ID");
					this.OnNN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NN_Ten", DbType="NVarChar(50)")]
		public string NN_Ten
		{
			get
			{
				return this._NN_Ten;
			}
			set
			{
				if ((this._NN_Ten != value))
				{
					this.OnNN_TenChanging(value);
					this.SendPropertyChanging();
					this._NN_Ten = value;
					this.SendPropertyChanged("NN_Ten");
					this.OnNN_TenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NgonNgu_Sach", Storage="_Saches", ThisKey="NN_ID", OtherKey="S_NgonNguID")]
		public EntitySet<Sach> Saches
		{
			get
			{
				return this._Saches;
			}
			set
			{
				this._Saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.NgonNgu = this;
		}
		
		private void detach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.NgonNgu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Management.NhaCungCap")]
	public partial class NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NCC_ID;
		
		private string _NCC_Ten;
		
		private string _NCC_DiaChi;
		
		private string _NCC_DienThoai;
		
		private string _NCC_Email;
		
		private System.Guid _rowguid;
		
		private EntitySet<PhieuNhap> _PhieuNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNCC_IDChanging(int value);
    partial void OnNCC_IDChanged();
    partial void OnNCC_TenChanging(string value);
    partial void OnNCC_TenChanged();
    partial void OnNCC_DiaChiChanging(string value);
    partial void OnNCC_DiaChiChanged();
    partial void OnNCC_DienThoaiChanging(string value);
    partial void OnNCC_DienThoaiChanged();
    partial void OnNCC_EmailChanging(string value);
    partial void OnNCC_EmailChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public NhaCungCap()
		{
			this._PhieuNhaps = new EntitySet<PhieuNhap>(new Action<PhieuNhap>(this.attach_PhieuNhaps), new Action<PhieuNhap>(this.detach_PhieuNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCC_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int NCC_ID
		{
			get
			{
				return this._NCC_ID;
			}
			set
			{
				if ((this._NCC_ID != value))
				{
					this.OnNCC_IDChanging(value);
					this.SendPropertyChanging();
					this._NCC_ID = value;
					this.SendPropertyChanged("NCC_ID");
					this.OnNCC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCC_Ten", DbType="NVarChar(100)")]
		public string NCC_Ten
		{
			get
			{
				return this._NCC_Ten;
			}
			set
			{
				if ((this._NCC_Ten != value))
				{
					this.OnNCC_TenChanging(value);
					this.SendPropertyChanging();
					this._NCC_Ten = value;
					this.SendPropertyChanged("NCC_Ten");
					this.OnNCC_TenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCC_DiaChi", DbType="NVarChar(250)")]
		public string NCC_DiaChi
		{
			get
			{
				return this._NCC_DiaChi;
			}
			set
			{
				if ((this._NCC_DiaChi != value))
				{
					this.OnNCC_DiaChiChanging(value);
					this.SendPropertyChanging();
					this._NCC_DiaChi = value;
					this.SendPropertyChanged("NCC_DiaChi");
					this.OnNCC_DiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCC_DienThoai", DbType="VarChar(20)")]
		public string NCC_DienThoai
		{
			get
			{
				return this._NCC_DienThoai;
			}
			set
			{
				if ((this._NCC_DienThoai != value))
				{
					this.OnNCC_DienThoaiChanging(value);
					this.SendPropertyChanging();
					this._NCC_DienThoai = value;
					this.SendPropertyChanged("NCC_DienThoai");
					this.OnNCC_DienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCC_Email", DbType="NVarChar(100)")]
		public string NCC_Email
		{
			get
			{
				return this._NCC_Email;
			}
			set
			{
				if ((this._NCC_Email != value))
				{
					this.OnNCC_EmailChanging(value);
					this.SendPropertyChanging();
					this._NCC_Email = value;
					this.SendPropertyChanged("NCC_Email");
					this.OnNCC_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_PhieuNhap", Storage="_PhieuNhaps", ThisKey="NCC_ID", OtherKey="PN_NhaCungCapID")]
		public EntitySet<PhieuNhap> PhieuNhaps
		{
			get
			{
				return this._PhieuNhaps;
			}
			set
			{
				this._PhieuNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuNhaps(PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_PhieuNhaps(PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Management.PhieuNhap")]
	public partial class PhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PN_ID;
		
		private System.Nullable<System.DateTime> _PN_NgayNhap;
		
		private System.Nullable<int> _PN_NhaCungCapID;
		
		private System.Guid _rowguid;
		
		private EntitySet<ChiTietPhieuNhap> _ChiTietPhieuNhaps;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPN_IDChanging(int value);
    partial void OnPN_IDChanged();
    partial void OnPN_NgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnPN_NgayNhapChanged();
    partial void OnPN_NhaCungCapIDChanging(System.Nullable<int> value);
    partial void OnPN_NhaCungCapIDChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    #endregion
		
		public PhieuNhap()
		{
			this._ChiTietPhieuNhaps = new EntitySet<ChiTietPhieuNhap>(new Action<ChiTietPhieuNhap>(this.attach_ChiTietPhieuNhaps), new Action<ChiTietPhieuNhap>(this.detach_ChiTietPhieuNhaps));
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PN_ID
		{
			get
			{
				return this._PN_ID;
			}
			set
			{
				if ((this._PN_ID != value))
				{
					this.OnPN_IDChanging(value);
					this.SendPropertyChanging();
					this._PN_ID = value;
					this.SendPropertyChanged("PN_ID");
					this.OnPN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN_NgayNhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> PN_NgayNhap
		{
			get
			{
				return this._PN_NgayNhap;
			}
			set
			{
				if ((this._PN_NgayNhap != value))
				{
					this.OnPN_NgayNhapChanging(value);
					this.SendPropertyChanging();
					this._PN_NgayNhap = value;
					this.SendPropertyChanged("PN_NgayNhap");
					this.OnPN_NgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PN_NhaCungCapID", DbType="Int")]
		public System.Nullable<int> PN_NhaCungCapID
		{
			get
			{
				return this._PN_NhaCungCapID;
			}
			set
			{
				if ((this._PN_NhaCungCapID != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPN_NhaCungCapIDChanging(value);
					this.SendPropertyChanging();
					this._PN_NhaCungCapID = value;
					this.SendPropertyChanged("PN_NhaCungCapID");
					this.OnPN_NhaCungCapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhap_ChiTietPhieuNhap", Storage="_ChiTietPhieuNhaps", ThisKey="PN_ID", OtherKey="CTPN_PhieuNhapID")]
		public EntitySet<ChiTietPhieuNhap> ChiTietPhieuNhaps
		{
			get
			{
				return this._ChiTietPhieuNhaps;
			}
			set
			{
				this._ChiTietPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_PhieuNhap", Storage="_NhaCungCap", ThisKey="PN_NhaCungCapID", OtherKey="NCC_ID", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.PhieuNhaps.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.PhieuNhaps.Add(this);
						this._PN_NhaCungCapID = value.NCC_ID;
					}
					else
					{
						this._PN_NhaCungCapID = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuNhaps(ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhap = this;
		}
		
		private void detach_ChiTietPhieuNhaps(ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhap = null;
		}
	}
}
#pragma warning restore 1591
