//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_SQL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\KHACHHANG;Initial Catalog=Nhom_Solo;Persist Security Info=T" +
            "rue;User ID=loginKhachHang;Password=tanda")]
        public string Nhom_SoloConnectionString {
            get {
                return ((string)(this["Nhom_SoloConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\KHACHHANG;Initial Catalog=Nhom_Solo;Persist Security Info=T" +
            "rue;User ID=loginKhachHang")]
        public string Nhom_SoloConnectionString1 {
            get {
                return ((string)(this["Nhom_SoloConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\NHAXUATBAN;Initial Catalog=Nhom_Solo;Persist Security Info=" +
            "True;User ID=loginXuatBan")]
        public string Nhom_SoloConnectionString2 {
            get {
                return ((string)(this["Nhom_SoloConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-IAK7P2M\\KHACHHANG;Initial Catalog=Nhom_Solo;User ID=sa;Connec" +
            "t Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string Nhom_SoloConnectionString3 {
            get {
                return ((string)(this["Nhom_SoloConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-IAK7P2M\\NHAXUATBAN;Initial Catalog=Nhom_Solo;User ID=sa;Conne" +
            "ct Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string Nhom_SoloConnectionString4 {
            get {
                return ((string)(this["Nhom_SoloConnectionString4"]));
            }
        }
    }
}
